[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "relativistic_eocs"
authors = [{name = "Dylan Watt", email = "dylan@kadre.io"}]
dynamic = ["version", "description"]
